apiVersion: v1
kind: Secret
metadata:
  name: payment-db-secret
  namespace: default
type: Opaque
data:
  # These values should be base64 encoded
  # Use: echo -n 'your-value' | base64
  host: <BASE64_ENCODED_RDS_ENDPOINT>
  username: <BASE64_ENCODED_DB_USERNAME>
  password: <BASE64_ENCODED_DB_PASSWORD>

---
apiVersion: v1
kind: Secret
metadata:
  name: payment-redis-secret
  namespace: default
type: Opaque
data:
  # These values should be base64 encoded
  host: <BASE64_ENCODED_REDIS_ENDPOINT>

---
# ConfigMap for non-sensitive configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: default
data:
  application-kubernetes.yml: |
    server:
      port: 8080
    
    spring:
      application:
        name: payment-service
      jpa:
        show-sql: false
        hibernate:
          ddl-auto: validate
      flyway:
        enabled: true
        baseline-on-migrate: true
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: when-authorized
    
    logging:
      level:
        com.trading.payments: INFO
        root: WARN
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    
    payment:
      fraud:
        max-score: 100
        decline-threshold: 50