# Local development configuration

server:
  port: 8080

spring:
  application:
    name: payment-service
  
  # Exclude Redis repositories from auto-configuration  
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
    
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:trading_platform}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:localpassword}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true  # Enable for local debugging
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

# Actuator for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Logging - more verbose for local dev
logging:
  level:
    com.trading.payments: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Custom payment configuration
payment:
  fraud:
    max-score: 100
    decline-threshold: 50
  processing:
    timeout-seconds: 30