apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processor
  namespace: default
  labels:
    app: data-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-processor
  template:
    metadata:
      labels:
        app: data-processor
    spec:
      containers:
      - name: data-processor
        image: joshskkim/data-processor:v1.0.0  # UPDATE THIS
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: data-processor
  labels:
    app: data-processor
spec:
  ports:
  - port: 80
    targetPort: 8000
    name: http
  selector:
    app: data-processor